require 'rack/test'
require 'rspec/its'
include Rack::Test::Methods

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

def app
  Sinatra::Application
end

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.order = 'random'
end

def payload
  JSON.parse(GITHUB_JSON)
end

SETTINGS_YAML = <<-eof
---
applications:
  - name: Movielala
    path: /var/www/vhosts/movielala.com/staging/
    git: git@github.com:movielala/api.git
    chat_integration: SlackIntegration
    api_token: 182efbfc0aceda25182c8d982a2e1dfd
eof

GITHUB_JSON = <<-GITHUB_JSON
  { 
    "before": "5aef35982fb2d34e9d9d4502f6ede1072793222d",
    "repository": {
      "url": "http://github.com/defunkt/github",
      "name": "github",
      "owner": {
        "email": "chris@ozmm.org",
        "name": "defunkt" 
      }
    },
    "commits": {
      "41a212ee83ca127e3c8cf465891ab7216a705f59": {
        "url": "http://github.com/defunkt/github/commit/41a212ee83ca127e3c8cf465891ab7216a705f59",
        "author": {
          "email": "chris@ozmm.org",
          "name": "Chris Wanstrath" 
        },
        "message": "okay i give in",
        "timestamp": "2008-02-15T14:57:17-08:00" 
      },
      "de8251ff97ee194a289832576287d6f8ad74e3d0": {
        "url": "http://github.com/defunkt/github/commit/de8251ff97ee194a289832576287d6f8ad74e3d0",
        "author": {
          "email": "chris@ozmm.org",
          "name": "Chris Wanstrath" 
        },
        "message": "update pricing a tad",
        "timestamp": "2008-02-15T14:36:34-08:00" 
      }
    },
    "after": "de8251ff97ee194a289832576287d6f8ad74e3d0",
    "ref": "refs/heads/features/awesome-feature" 
  }
GITHUB_JSON
